# **HW-04**
Данилевского Александра

In [2]:
import numpy as np
import random

<div style="clear:both;"></div>
<hr style="float:left;width:100%;border-top: 3px double #8c8b8b;">
<div style="clear:both;"></div>

# Аттрактор Лоренца

##  Задача №1. Простое решение

<br>
<font size=4> 
Система
</font>
<br>
<br>
$
\Large
\begin{cases}
   \dot{x} = \sigma (y - x), 
   \\
   \dot{y} = x (\rho - z) - y,
   \\
   \dot{z} = x y - \beta z
 \end{cases}\normalsize
 $
<br>
<font size=4> 
Стандартные значения - $\sigma=10, \rho=28, \beta=2.667$
</font>
<br>

__Требования__:
- Не использовать интеграторы и массивы numpy, точки высчитывать в цикле
- Начальные данные - $(0., 1., 1.01)$
- Количество точек - $10^4$
- Подписать рисунок и оси
- label со значениями $\sigma=10, \rho=28, \beta=2.667$


In [4]:
#%%writefile my_pkg/lorenz.py
#'Пакет для построения графика аттрактора Лоренца'

def plotLorenzAttractor(xx, yy, zz,*,sigma = 10, rho = 28, beta = 2.667):
    
    '''Построение графика решения системы Лоренца'''
    
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D
    
    fig = plt.figure()
    ax = fig.gca(projection='3d')
    ax.plot(xx, yy, zz, lw=0.5)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_title("Lorenz Attractor")
    ax.text(0,0,0, r'$\sigma={0}, \varrho={1}, \beta={2}$'.format(sigma,rho,beta),
            horizontalalignment='center',
            verticalalignment='center',
            transform = ax.transAxes)
    plt.show()

In [29]:
#%%writefile -a my_pkg/lorenz.py

def lorenzAttractor1(sigma = 10, rho = 28, beta = 2.667, initialdata = (0.,1.,1.01), dt = 0.01, npoint = 10**4, plot = True):
    
    '''Функция строит аттрактор Лоренца'''
    
    xx = [0]*(npoint); yy = [0]*(npoint); zz = [0]*(npoint)
    xx[0], yy[0], zz[0] = initialdata

    for i in range(npoint-1):
        dx = sigma*(yy[i] - xx[i])
        dy = xx[i]*(rho-zz[i])-yy[i]
        dz = xx[i]*yy[i] - beta*zz[i]
        xx[i + 1] = (dx * dt)+xx[i]
        yy[i + 1] = (dy * dt)+yy[i]
        zz[i + 1] = (dz * dt)+zz[i]

    if plot: plotLorenzAttractor(xx, yy, zz)

<div style="clear:both;"></div>
<hr style="float:left;width:100%;border-top: 3px double #8c8b8b;">
<div style="clear:both;"></div>

##  Задача №2. Чуть сложнее

Аттрактор Лоренца, но другие требования:

- Использовать numpy массивы, не использовать интегрирование из scipy
- Начальные данные - $(0., 1., 1.01)$
- Количество точек - $10^4$
- Для вычисления очередной точки использовать специальную функцию `lorenz(...)`, причем
    - `lorenz(x, y, z)` считает производные при стандартных значениях $\sigma=10, \rho=28, \beta=2.667$
    - если нужны другие значения $\sigma, \rho, \beta$, то вызывать можно только как `lorenz(x, y, z, sigma=..., beta=..., rho=...)`
- Подписать рисунок и оси
- label со значениями $\sigma, \rho, \beta$, для которых построена фигура

In [30]:
#%%writefile -a my_pkg/lorenz.py

def lorenzAttractor2(sigma = 10, rho = 28, beta = 2.667, initialdata = (0.,1.,1.01), dt = 0.01, npoint = 10**4, plot = True):
    
    '''Построение графика решения системы Лоренца c использованием numpy'''
    
    import numpy as np
    
    xx = [0]*(npoint); yy = [0]*(npoint); zz = [0]*(npoint)
    xx[0], yy[0], zz[0] = initialdata
    
    def lorenz(u,*,sigma = 10, beta = 2.667, rho = 28):
        x,y,z=u
        return [sigma*(y - x), x*(rho-z)-y, x*y - beta*z]

    for i in range(npoint-1):   
        dx,dy,dz = lorenz((xx[i],yy[i],zz[i]))
        xx[i + 1] = dx*dt+xx[i]
        yy[i + 1] = dy*dt+yy[i]
        zz[i + 1] = dz*dt+zz[i]
        
    if plot: plotLorenzAttractor(xx, yy, zz)
    

<div style="clear:both;"></div>
<hr style="float:left;width:100%;border-top: 3px double #8c8b8b;">
<div style="clear:both;"></div>

##  Задача №3. Сложнее, но короче

Аттрактор Лоренца, но требования опять поменялись:

- Использовать numpy массивы и интегрирование из scipy (odeint)
- Начальные данные - $(0., 1., 1.01)$
- Временной интервал - $0...100$
- Количество точек - $10^4$
- Для вычисления очередной точки использовать специальную функцию `lorenz(...)`, причем первый аргумент - кортеж из трех точек; остальное - как в _задаче №2_ (может что-то ещё понадобится, посмотрите сигнатуру `odeint`)
- Подписать рисунок и оси
- label со значениями $\sigma, \rho, \beta$, для которых построена фигура

In [32]:
#%%writefile -a my_pkg/lorenz.py

def lorenzAttractor3(sigma = 10, rho = 28, beta = 2.667, initialdata = (0.,1.,1.01), npoint = 10**4, plot = True):
    '''Построение графика решения системы Лоренца c использованием numpy'''

    import numpy as np
    from scipy.integrate import odeint
    
    def lorenz(u,t,*,sigma = 10, beta = 2.667, rho = 28):
        x,y,z=u
        return [sigma*(y - x), x*(rho-z)-y, x*y - beta*z]
    
    t = np.linspace(0, 100, npoint)
    w = odeint(lorenz, initialdata, t)

    if plot: plotLorenzAttractor(w[:,0], w[:,1], w[:,2])
    

<div style="clear:both;"></div>
<hr style="float:left;width:100%;border-top: 3px double #8c8b8b;">
<div style="clear:both;"></div>

## Задача №4

Поместите три написанные функции в собственный пакет

In [413]:
%mkdir my_pkg

In [1]:
%%writefile my_pkg/__init__.py
#!/usr/bin/env python3

Writing my_pkg/__init__.py


<div style="clear:both;"></div>
<hr style="float:left;width:100%;border-top: 3px double #8c8b8b;">
<div style="clear:both;"></div>

##  Задача №5. Опциональная

Сравните скорости выполнения написанных функций

In [36]:
%timeit lorenzAttractor1(plot = False)

9.89 ms ± 210 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
%timeit lorenzAttractor2(plot = False)

12 ms ± 362 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [38]:
%timeit lorenzAttractor3(plot = False)

131 ms ± 2.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


<div style="clear:both;"></div>
<hr style="float:left;width:100%;border-top: 3px double #8c8b8b;">
<div style="clear:both;"></div>

## Задача №6

- сгенерируйте список чисел от 1 до произвольного числа $n$ от 5 до 9 включительно
- сделайте из него массив numpy
- сгенерируйте случайное число $m$ от 2 до 4 включительно
- верните массив numpy в следующей формы: $[1, 0, ..., 0, 2, 0, ..., 0, 3, ... , n, 0, ... , 0]$, где количество нулей между числами равно $m$
- преобразуйте полученный массив в двумерный массив так, чтобы в первом столбце были числа $1,2, ... , n$, остальные - $0$

In [53]:
n = random.randint(5, 9)
m = random.randint(2, 4)
print('n = ', n, '; m = ', m)
a = np.array(list(range(1,n+1)))
z = [0]*m
print('a = ', a)
for i in range(n, 0, -1):
    a= np.insert(a,i,z)
print('a = ', a)
a.shape = n,m+1
print('a = ', a)

n =  6 ; m =  4
a =  [1 2 3 4 5 6]
a =  [1 0 0 0 0 2 0 0 0 0 3 0 0 0 0 4 0 0 0 0 5 0 0 0 0 6 0 0 0 0]
a =  [[1 0 0 0 0]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]
 [6 0 0 0 0]]
